export enum BusyAction {
    FetchingCollectors,
    UpdatingCollector,
    DeletingCollector,
    FetchingMiners,
    CreatingMiner,
    UpdatingMiner,
    DeleteMiner,
    FetchingSnapshots,
    FetchingUsers,
    CreatingUser,
    UpdatingUser,
    DeleteUser,
    FetchingSettings,
    UpdatingSettings,
    LoggingIn,
}
