export enum ActionType {
    Busy,
    NotBusy,
    FetchAllCollectorsSuccess,
    UpdateCollectorSuccess,
    FetchAllMinersSuccess,
    CreateMinerSuccess,
    UpdateMinerSuccess,
    DeleteMinerSuccess,
    FetchSnapshotsSuccess,
    FetchAllUsersSuccess,
    CreateUserSuccess,
    DeleteUserSuccess,
    FetchAllSettingsSuccess,
    UpdateSettingsSuccess,
    Validation,
    LoginSuccess,
}
